// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: sysmon.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Sysmon_ProbeQuery_FullMethodName = "/api.sysmon/ProbeQuery"
)

// SysmonClient is the client API for Sysmon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysmonClient interface {
	ProbeQuery(ctx context.Context, in *Query, opts ...grpc.CallOption) (Sysmon_ProbeQueryClient, error)
}

type sysmonClient struct {
	cc grpc.ClientConnInterface
}

func NewSysmonClient(cc grpc.ClientConnInterface) SysmonClient {
	return &sysmonClient{cc}
}

func (c *sysmonClient) ProbeQuery(ctx context.Context, in *Query, opts ...grpc.CallOption) (Sysmon_ProbeQueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &Sysmon_ServiceDesc.Streams[0], Sysmon_ProbeQuery_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &sysmonProbeQueryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Sysmon_ProbeQueryClient interface {
	Recv() (*Data, error)
	grpc.ClientStream
}

type sysmonProbeQueryClient struct {
	grpc.ClientStream
}

func (x *sysmonProbeQueryClient) Recv() (*Data, error) {
	m := new(Data)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SysmonServer is the server API for Sysmon service.
// All implementations must embed UnimplementedSysmonServer
// for forward compatibility
type SysmonServer interface {
	ProbeQuery(*Query, Sysmon_ProbeQueryServer) error
	mustEmbedUnimplementedSysmonServer()
}

// UnimplementedSysmonServer must be embedded to have forward compatible implementations.
type UnimplementedSysmonServer struct {
}

func (UnimplementedSysmonServer) ProbeQuery(*Query, Sysmon_ProbeQueryServer) error {
	return status.Errorf(codes.Unimplemented, "method ProbeQuery not implemented")
}
func (UnimplementedSysmonServer) mustEmbedUnimplementedSysmonServer() {}

// UnsafeSysmonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysmonServer will
// result in compilation errors.
type UnsafeSysmonServer interface {
	mustEmbedUnimplementedSysmonServer()
}

func RegisterSysmonServer(s grpc.ServiceRegistrar, srv SysmonServer) {
	s.RegisterService(&Sysmon_ServiceDesc, srv)
}

func _Sysmon_ProbeQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Query)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SysmonServer).ProbeQuery(m, &sysmonProbeQueryServer{stream})
}

type Sysmon_ProbeQueryServer interface {
	Send(*Data) error
	grpc.ServerStream
}

type sysmonProbeQueryServer struct {
	grpc.ServerStream
}

func (x *sysmonProbeQueryServer) Send(m *Data) error {
	return x.ServerStream.SendMsg(m)
}

// Sysmon_ServiceDesc is the grpc.ServiceDesc for Sysmon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sysmon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.sysmon",
	HandlerType: (*SysmonServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProbeQuery",
			Handler:       _Sysmon_ProbeQuery_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sysmon.proto",
}
